# Generated by Django 4.2.7 on 2023-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', 'state_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateconfig',
            name='monthly_tax_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
