# Generated by Django 4.2.7 on 2023-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_quote_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='coverage_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=10),
        ),
    ]
